### ISSUE TITLE
make a fresh release of this module / make tag of old release

### ISSUE THREAD

**Issue by igalic** [smoeding/puppet-haveged#1]
this module was first / last released on [Jun 9th 2015](https://forge.puppetlabs.com/stm/haveged).
there's no indication in this source code that reflects that (i.e.: no tag)

please make an appropriate tag from the old release / and or make a new release if you find that appropriate.

**Comment by smoeding** [comment]
Thanks for pointing that out. Yes, I forgot the tag. The module is not yet ready for a new release. Therefore I added a tag to the commit of the v0.1.0 release.

**Comment by igalic** [comment]
cool thanks!
